services:
  - type: web
    name: veestores-backend
    env: python
    repo: .
    branch: main
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn run:app --chdir backend --bind 0.0.0.0:$PORT"
    plan: starter
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: SECRET_KEY
        value: "416100980803"
      - key: ADMIN_EMAIL
        value: "veestores@outlook.com"
      - key: ADMIN_PASSWORD
        value: "admin1234"
      - key: STRIPE_SECRET_KEY
        value: ""
      - key: MAIL_SERVER
        value: "veestore@outlook.com"
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: "veestores"
      - key: MAIL_PASSWORD
        value: "12345678qq"
      - key: MAIL_USE_TLS
        value: "true"
      - key: FLASK_ENV
        value: "production"

  - type: web
    name: veestores-frontend
    env: python
    repo: .
    branch: main
    buildCommand: "pip install -r frontend/requirements.txt"
    startCommand: "gunicorn run:app --chdir frontend --bind 0.0.0.0:$PORT"
    plan: starter
    envVars:
      - key: BACKEND_API
        value: "https://veestoresbcknd.onrender.com"
